version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y git
      - apt-get install -y jq
      - apt-get install openssh-server
      - service ssh restart
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mv key id_rsa
      - cp id_rsa ~/.ssh/
      - git clone -b dev  git@github.com:sourcefuse/dealer-xtension.git
      - cd dealer-xtension
      - DEPLOY_REVISION=`git log -1 | grep "commit" | cut -d " " -f 2`
      - DEPLOY_USER=`git log -1 | grep "Author" | cut -d " " -f 2`
      - DEPLOY_DESCRIPTION=`git log -1 | grep "Date"` 
      - DEPLOY_CHANGELOG=`git log -1 | awk 'NR==1{next}NR==2{next}NR==3{next}NR==4{next}1'`   
      - chmod +x nrd
      - ./nrd -a Dealer-extension -c $DEPLOY_CHANGELOG -d DEPLOY_DESCRIPTION -r $DEPLOY_REVISION -u $DEPLOY_USER
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
